// frontend/src/app/about-page/about-page.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ThemeService } from '../services/theme.service';

@Component({
  selector: 'app-about-page',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './about-page.component.html',
  styleUrls: ['./about-page.component.scss']
})
export class AboutPageComponent {
  public theme = inject(ThemeService);

  get isDark() {
    return this.theme.isDark();
  }
}

<div class="about-page font-sans" [ngClass]="isDark ? 'bg-black text-white' : 'bg-white text-black'">
  <main class="container">
    
    <!-- Hero Section -->
    <header class="hero-section">
      <span class="section-label">Since 2024</span>
      <h1 class="font-serif">The Blog Network</h1>
      <p class="hero-lead">
        A platform built for deep learning, technical discovery, and high-fidelity storytelling.
      </p>
    </header>

    <!-- Cinematic Image -->
    <div class="featured-image-wrapper">
      <img 
        src="https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=80&w=1200"
        alt="Modern architecture"
        class="featured-img"
      >
    </div>

    <!-- Mission -->
    <div class="mission-grid">
      <h2 class="font-serif">Our Mission</h2>
      <div class="text-content">
        <p>
          In a world of constant noise and distraction, we believe in the power of clarity. 
          The Blog Network was founded on the principle that great content deserves 
          great presentation—clean, focused, and beautiful.
        </p>
        <p>
          We cover topics ranging from design and technology to lifestyle and productivity, 
          always with an emphasis on depth over breadth, quality over quantity.
        </p>
      </div>
    </div>

    <!-- Values -->
    <section class="values-section">
      <span class="section-label">Core Values</span>
      <div class="values-grid">
        <div class="value-card">
          <h3>Simplicity</h3>
          <p>
            We strip away the unnecessary to focus on what truly matters. 
            Every word and design element serves a purpose.
          </p>
        </div>

        <div class="value-card">
          <h3>Authenticity</h3>
          <p>
            We write about what we know and care about deeply. 
            Our content comes from real experience and genuine insight.
          </p>
        </div>

        <div class="value-card">
          <h3>Excellence</h3>
          <p>
            We believe in doing fewer things, but doing them exceptionally well. 
            Quality is never negotiable.
          </p>
        </div>
      </div>
    </section>

    <!-- Community CTA -->
    <section class="community-section">
      <h2 class="font-serif">Join the Journey</h2>
      <p>
        Subscribe to our newsletter to receive weekly design inspiration 
        and technical insights delivered directly to your inbox.
      </p>
      <button class="btn-primary">
        Subscribe Now
      </button>
    </section>

  </main>
</div>

// AboutPage.tsx
import { ImageWithFallback } from './figma/ImageWithFallback';

export function AboutPage() {
  return (
    <div className="min-h-screen bg-white">
      <main className="max-w-4xl mx-auto px-6 py-16">
        {/* Hero Section */}
        <div className="mb-16">
          <h1 
            style={{ 
              fontFamily: 'Playfair Display, serif',
              fontSize: '3.5rem',
              lineHeight: '1.2'
            }}
            className="mb-6 tracking-tight"
          >
            About The Modern Blog
          </h1>
          <p 
            className="text-gray-600"
            style={{ 
              fontFamily: 'Inter, sans-serif',
              fontSize: '1.25rem',
              lineHeight: '1.8'
            }}
          >
            A space dedicated to thoughtful writing, minimalist design, and meaningful conversations.
          </p>
        </div>

        {/* Featured Image */}
        <div className="relative overflow-hidden aspect-[16/9] mb-16">
          <ImageWithFallback 
            src="https://images.unsplash.com/photo-1524758631624-e2822e304c36?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjB3b3Jrc3BhY2V8ZW58MXx8fHwxNzY0NzA5NjgyfDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral"
            alt="About us"
            className="w-full h-full object-cover"
          />
        </div>

        {/* Content */}
        <div className="space-y-8">
          <section>
            <h2 
              style={{ fontFamily: 'Playfair Display, serif' }}
              className="mb-4 tracking-tight"
            >
              Our Mission
            </h2>
            <p 
              className="text-gray-800 mb-4"
              style={{ 
                fontFamily: 'Inter, sans-serif',
                fontSize: '1.125rem',
                lineHeight: '1.9'
              }}
            >
              In a world of constant noise and distraction, we believe in the power of clarity. The Modern Blog was founded on the principle that great content deserves great presentation—clean, focused, and beautiful.
            </p>
            <p 
              className="text-gray-800"
              style={{ 
                fontFamily: 'Inter, sans-serif',
                fontSize: '1.125rem',
                lineHeight: '1.9'
              }}
            >
              We cover topics ranging from design and technology to lifestyle and productivity, always with an emphasis on depth over breadth, quality over quantity.
            </p>
          </section>

          <section>
            <h2 
              style={{ fontFamily: 'Playfair Display, serif' }}
              className="mb-4 tracking-tight"
            >
              Our Values
            </h2>
            <div className="space-y-6">
              <div>
                <h3 
                  style={{ fontFamily: 'Playfair Display, serif' }}
                  className="mb-2 tracking-tight"
                >
                  Simplicity
                </h3>
                <p 
                  className="text-gray-800"
                  style={{ 
                    fontFamily: 'Inter, sans-serif',
                    fontSize: '1.125rem',
                    lineHeight: '1.9'
                  }}
                >
                  We strip away the unnecessary to focus on what truly matters. Every word, every design element serves a purpose.
                </p>
              </div>

              <div>
                <h3 
                  style={{ fontFamily: 'Playfair Display, serif' }}
                  className="mb-2 tracking-tight"
                >
                  Authenticity
                </h3>
                <p 
                  className="text-gray-800"
                  style={{ 
                    fontFamily: 'Inter, sans-serif',
                    fontSize: '1.125rem',
                    lineHeight: '1.9'
                  }}
                >
                  We write about what we know and care about deeply. Our content comes from real experience and genuine insight.
                </p>
              </div>

              <div>
                <h3 
                  style={{ fontFamily: 'Playfair Display, serif' }}
                  className="mb-2 tracking-tight"
                >
                  Excellence
                </h3>
                <p 
                  className="text-gray-800"
                  style={{ 
                    fontFamily: 'Inter, sans-serif',
                    fontSize: '1.125rem',
                    lineHeight: '1.9'
                  }}
                >
                  We believe in doing fewer things, but doing them exceptionally well. Quality is never negotiable.
                </p>
              </div>
            </div>
          </section>

          <section className="border-t border-gray-200 pt-12">
            <h2 
              style={{ fontFamily: 'Playfair Display, serif' }}
              className="mb-4 tracking-tight"
            >
              Join Our Community
            </h2>
            <p 
              className="text-gray-800 mb-6"
              style={{ 
                fontFamily: 'Inter, sans-serif',
                fontSize: '1.125rem',
                lineHeight: '1.9'
              }}
            >
              Subscribe to our newsletter to receive new articles, design inspiration, and thoughtful insights delivered to your inbox every week.
            </p>
            <button
              className="px-8 py-3 text-white rounded-lg hover:opacity-90 transition-opacity"
              style={{ 
                backgroundColor: 'var(--accent-blog)',
                fontFamily: 'Inter, sans-serif'
              }}
            >
              Subscribe Now
            </button>
          </section>
        </div>
      </main>
    </div>
  );
}
